services:
  redis:
   image: redis
   logging:
      driver: none 
   ports:
      - "6379:6379"

  rabbitmq:
   image: rabbitmq:3.13.2-management
   logging:
      driver: none
   hostname: my-rabbit
   environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
   ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
